### PR TITLE
add experimental due support

### PR DESCRIPTION
**Pull request by jmriego**
this would give Fino support for Arduino Due which was requested in #3

### CODE REVIEW

**Comment by SchmidtFranz** [comment]
Oh nice to see that you are still working to support Arduino due.
Im still Working on my stick project but decided to develop my own motor drivers wich takes a bit longer than anticipated. 3-4 months and then I'm back to this. ; )

**Comment by jmriego** [comment]
yes, someone gave me a Due to test this and finally this version works! it was tricky as the Due USB libraries have a few issues and it was not even possible to debug it printing to Serial. I had to debug this with blinking lights and stuff like that.
I'm still reading through the documents to see where this can break but so far all effects seem fine

**Comment by SchmidtFranz** [comment]
Last year when I tried it i didn't even know where to start with this when it didn't work on due. Because the joystick library fino builds upon works on due.

**Comment by jmriego** [comment]
the two issues were that only some messages were received and the variables were mangled.
So it started receiving FFB messages but if let's say it has to receive 20 messages to set up the effects, it hanged on the 3th or 4th. Something related to the buffer filling too fast I think
Also, as the data was received in wrong order, variables like gain, effect duration, etc. were all mangled

I have to check if there's some weird condition that this is not taking into account now but at least seems like it's in an usable state

**Comment by jmriego** [comment]
hi @SchmidtFranz ! I have made some more changes to this and simplified the code a lot. I have done lots of testing in both an Arduino Due and a Micro so I think this is ready to go. If you are playing with this and find some issue please let me know!

**Comment by SchmidtFranz** [comment]
Thanks for the work on this, I'm definitely still on this, but i lack the time atm because I just moved, my diy servo drive is still in the works, but in the meantime i probably will try it on the Microsoft sidewinder and replace the electronics in it.

**Comment by jmriego** [comment]
no problem at all. If you end up not having time I'll just merge it anyway and if you end up finding any problem just let me know. I haven't found any problems with the tests I've thrown at it and I was able to add some compile test to ensure nothing breaks in the future

**Comment by SchmidtFranz** [comment]
In the next few weeks not, i think you should just merge it, as far as I can tell some people from the eagle forum use it too, maybe it helps them.

**Comment by jmriego** [comment]
cool. I'll do that then. Thanks!

**Pull request merged**
